[package]
name = "rustlang_discord_mod_bot"
version = "0.1.0"
authors = ["technetos <mrgould93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.6.0-rc.0", features = ["cache", "http", "model"] }
